# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Topdish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Topdish

  target 'TopdishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TopdishUITests' do
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn', '< 5.0.0'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'

end
